stages:
- build-master
- trigger-cryports-build

build-master:
  stage: build-master
  script:
    - make dbuild-cryptos-base-noarch
  only:
    - master

trigger-cryports-build:
  stage: trigger-cryports-build
  script:
    - "curl -X POST -F token=d7c2cf09ba5fd5d6e6a07363719807 -F ref=develop http://gitlab.engr.atlas/api/v4/projects/30/trigger/pipeline"
